---
- hosts: all
  become: yes
  vars:
    db_name: e4e_prod
    db_pass: e4elab
    db_user: e4e_db
  tasks:
 
    - name: Copy repo template to sources.list
      action: copy src=../templates/pg-repo dest=/etc/apt/sources.list.d/pgdg.list

    - name: Import gpg keys
      action: command /usr/bin/wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: update apt
      action: command /usr/bin/apt-get update

    - name: update cache
      apt: update_cache=yes

    - name: Install Postgres 9.6
      apt: name=$item state=installed
      with_items:
        - postgresql-9.6
        - libpq-dev
        - python-psycopg2
        - postgresql-server-dev-9.6
        - postgresql-contrib-9.6
        - postgresql-client-9.6

    - name: update postgres db configuration
      action: copy src=../templates/postgresql.conf dest=/etc/postgresql/9.6/main/postgresql.conf

    - name: update postgres client configuration
      action: template src=/templates/pg_hba.conf dest=/etc/postgresql/9.6/main/pg_hba.conf

    - name: start postgresql
      service: name=postgresql state=restarted enabled=yes

    - name: Setup postgres database
      become_user: postgres
      postgresql_db: name={{ db_name }} state=present

    - name: Setup database user
      become_user: postgres
      postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_pass }} priv=ALL
