---
- hosts: all
  vars_files:
    - ../vars.yml
  become: yes
 
  tasks:
 
    - name: Copy repo template to sources.list.d
      action: copy src=../templates/pg-repo.j2 dest=/etc/apt/sources.list.d/pgdg.list

    - name: Import gpg keys
      apt_key: 
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Update cache
      apt: 
        update_cache: yes

    - name: Install Postgres 9.6
      apt: name={{ item }} state=present
      with_items:
        - postgresql-9.6
        - libpq-dev
        - python-psycopg2
        - postgresql-server-dev-9.6
        - postgresql-contrib-9.6
        - postgresql-client-9.6

    - name: Create and set ownership of Log directory
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: postgres
        recurse: yes

    - name: Create and set ownership of Data directory
      file: 
        path: "{{ data_dir }}" 
        state: directory
        owner: postgres
        recurse: yes
 
    - name: Initialize new PostgreSQL 9.6 cluster on server
      become_user: postgres
      command: "{{ pg_bin }}/initdb -D {{ data_dir }} -A trust"
      ignore_errors: yes

    - name: Start PostgreSQL
      command: /etc/init.d/postgresql start
#      ignore_errors: yes

    - name: Setup postgres database
      become_user: postgres
      postgresql_db: name={{ db_name }} state=present

    - name: Setup database user
      become_user: postgres
      postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_pass }} priv=ALL

    - name: update postgres db configuration
      action: copy src=../templates/postgresql.j2 dest=/var/lib/postgresql/9.6/main/postgresql.conf

    - name: update postgres client configuration
      action: template src=../templates/pg_hba.j2 dest=/var/lib/postgresql/9.6/main/pg_hba.conf

#    - name: Copy Postgresql service template to systemd 
#      action: copy src=../templates/postgresql.service dest=/lib/systemd/system/postgresql.service mode=644

    - name: reload systemd
      command: systemctl daemon-reload

    - name: Restart Postgresql
      command: /etc/init.d/postgresql restart

    - name: Reboot required
      command: ( /bin/sleep 5 ; shutdown -r now ) & removes=/var/run/reboot-required
      async: 30
      poll: 0
      ignore_errors: true
      notify:
        - waiting for server to come back

  handlers:
     - name: waiting for server to come back
       local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=60
       become: no

