---
- hosts: all

   tasks:

      - name: Import gpg keys
        action: command /usr/bin/curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh      

      - name: Run node script
        action: command /usr/bin/bash nodesource_setup.sh
        become: yes

      - name: Install nodejs
        apt: name=nodejs
        become: yes
