---
- hosts: all
  become: yes

  tasks:
  
      - name: Import gpg keys
        command: /usr/bin/curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
        args:
          chdir: /home/test
      
      - name: Make script executable
        file: 
          path: /home/test/nodesource_setup.sh
          owner: test
          mode: 0775

      - name: Run node script 
        command: /home/test/nodesource_setup.sh

      - name: Install nodejs
        apt: name={{ item }} state=installed
        with_items:
          - nodejs
